security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: in_memory
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /admin
            logout:
                path: app_logout
                target: app_home_page
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # Remember me for 30 days (in seconds)
                name: 'REMEMBERME'
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }