version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    # prod beží na MariaDB (hostcreators.sk), preto tu používame rovnaký engine
    image: mariadb:${MARIADB_VERSION:-10.5}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
